version: '3'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: task_tracker
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U root -d task_tracker" ]
      interval: 10s
      timeout: 5s
      retries: 10

  liquibase:
    image: liquibase/liquibase
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./src/main/resources/db/changelog:/liquibase/changelog
    command: >
      --url=jdbc:postgresql://postgres:5432/task_tracker
      --username=root
      --password=root
      --changelog-file=changelog/changelog.xml
      update
    restart: on-failure

  tomcat:
    build: .
    container_name: tomcat
    ports:
      - "8080:8080"
    depends_on:
      liquibase:
        condition: service_completed_successfully

volumes:
  postgres_data:
